### ISSUE TITLE
Fresh install of authjs-nuxt is not worknig on vercel-edge

### ISSUE THREAD

**Issue by sphex813** [Hebilicious/authjs-nuxt#75]
### Environment

    "@auth/core": "^0.10.4",
    "nuxt": "^3.6.3"
    "@hebilicious/authjs-nuxt": "^0.3.0-beta.2",
    "nitropack": "npm:nitropack-edge@latest"
    "h3": "1.8.0-rc.3", 

### Reproduction

1. Create nuxt 3 application
2. Follow getting started steps from this module https://authjs-nuxt.pages.dev/getting-started.html
3. Deploy application on the vercel with NITRO_PRESET="vercel-edge"

### Describe the bug

Following steps in getting started in documentation  and deploying on the vercel-edge leads to not working application.
I created empty nuxt 3 application and installed this module, but after deploying on vercel-edge I am getting error
<img width="622" alt="image" src="https://github.com/Hebilicious/authjs-nuxt/assets/26482886/31b1a597-b37b-42fb-8e88-fa12c8fd580d">
 
https://nuxt3-test-rho.vercel.app/
https://github.com/sphex813/nuxt3-test

**Comment by Hebilicious** [comment]
Hi, your repo is private. Could you also post the logs ?

**Comment by sphex813** [comment]
> Hi, your repo is private. Could you also post the logs ?

Oh sorry, now it should be public

**Comment by sphex813** [comment]
log from vercel is saying this: 
`TypeError: Cannot read properties of undefined (reading 'electron')
    at (index.mjs:1:118005)
    at (__nitro:middleware.js:1:17)`

**Comment by cosbgn** [comment]
@sphex813 this is caused by h3 override.


I have the same issue, and these are the logs: `npm ERR! Override for h3@^1.8.0-rc.3 conflicts with direct dependency`

If you remove the override, leaving only nitropack:

```js

  "overrides": {
    "nitropack": "npm:nitropack-edge@latest"
  },
  ```
  The deployment will work and the site won't crush. However You will probably reach another error: 
  ```js
[mf:inf] POST /api/auth/signin/google 500 Internal Server Error (9ms)
[nuxt] [request error] [unhandled] [500] CSRF protected
```
I'm trying to fix this now, if I get a solution I'll post it here, otherwise I'll open a new issue for this `CSRF protected` error (probably it comes because I remove the h3 override

**Comment by sphex813** [comment]
@cosbgn I tried to remove h3 override but it does the same thing after redeploy

**Comment by cosbgn** [comment]
Did you remove package-lock.json?

**Comment by sphex813** [comment]
@cosbgn yeah, but it seems that error has changed 
`
/__nitro
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at (index.mjs:1:177349)
    at (index.mjs:1:183128)
    at (index.mjs:1:183788)
    at (index.mjs:1:171124)
    at (index.mjs:1:183864)
    at (index.mjs:1:171124)
    at (index.mjs:1:199846)
    at (__nitro:middleware.js:1:17)`

**Comment by cosbgn** [comment]
I don't know, I'm also getting a ton of different issues and different error logs. If I manage to get it to work I'll post a comment, BTW I figured out that you can test `vercel-edge` locally with this:

```
npm run build && npx wrangler pages dev dist/
```
This will speed up things a bit. Please let me know if you get it to work!

**Comment by Hebilicious** [comment]
> @sphex813 this is caused by h3 override.
> 
> I have the same issue, and these are the logs: `npm ERR! Override for h3@^1.8.0-rc.3 conflicts with direct dependency`
> 
> If you remove the override, leaving only nitropack:
> 
> ```js
>   "overrides": {
>     "nitropack": "npm:nitropack-edge@latest"
>   },
> ```
> 
> The deployment will work and the site won't crush. However You will probably reach another error:
> 
> ```js
> [mf:inf] POST /api/auth/signin/google 500 Internal Server Error (9ms)
> [nuxt] [request error] [unhandled] [500] CSRF protected
> ```
> 
> I'm trying to fix this now, if I get a solution I'll post it here, otherwise I'll open a new issue for this `CSRF protected` error (probably it comes because I remove the h3 override

You have to set the baseUrl of your site in the nuxt config

**Comment by Hebilicious** [comment]
> I don't know, I'm also getting a ton of different issues and different error logs. If I manage to get it to work I'll post a comment, BTW I figured out that you can test `vercel-edge` locally with this:
> 
> ```
> npm run build && npx wrangler pages dev dist/
> ```
> 
> This will speed up things a bit. Please let me know if you get it to work!

This is for cloudflare_pages

**Comment by Hebilicious** [comment]
I have deployed `0.3.0-beta.2` on both cfp and vercel-edge. There might be a regression on the recent versions, I'll investigate

**Comment by sphex813** [comment]
So I have some new findings.
I tried to update my testing repo with the changes from @Hebilicious and that helped. So I did all the changes in my project repo but I was still getting the error. So i tried to move also `api/auth/[...].ts` from testing repo to project repo and it helped. So i tried to add things I deleted step by step. And as soon as I added ` adapter: PrismaAdapter(prisma)` it crashes again.
Do you have any suggestions how to make it work with prisma?

**Comment by Hebilicious** [comment]
@sphex813 please open a new issue with a minimal reproduction for your prisma related issue.
